# backend/Dockerfile
FROM python:3.11-slim

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN apt-get update && apt-get install -y build-essential && pip install --no-cache-dir -r requirements.txt

COPY . .

ENV YFINANCE_CACHE_DIR=/tmp/py-yfinance
RUN mkdir -p /tmp/py-yfinance

EXPOSE 5000
CMD ["gunicorn", "app:app", "--bind", "0.0.0.0:5000", "--workers", "3"]
